# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: zh # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

gist:
  noscript: false

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

paginate: 5
paginate_path: "/home/page:num"

sass:
  style: compressed
  
collections:
  life_posts:
    output: true
  letter_posts:
    output: true
  book_posts:
    output: true
  learner_posts:
    output: true
  song_posts:
    output: true
  family_posts:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "learner_posts"
    values:
      layout: "learn_post"
      author: "欧阳Boy_Petter"
  -
    scope:
      path: ""
      type: "song_posts"
    values:
      layout: "song_post"
      author: "欧阳Boy_Petter"
  -
    scope:
      path: ""
      type: "life_posts"
    values:
      layout: "life_post"
      author: "欧阳Boy_Petter"
  -
    scope:
      path: ""
      type: "letter_posts"
    values:
      layout: "letter_post"
      sendFrom: "欧阳Boy_Petter"
      cssType: "letter-1"
  -
    scope:
      path: ""
      type: "family_posts"
    values:
      layout: "family_post"
      author: "欧阳Boy_Petter"
      font: "Love"

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: 欧阳Boy_Petter's Blog
description: "个人GitHub博客."
keywords: 'java,IT,技术,blog'
author:
  name: "欧阳Boy_Petter"
  job_title:
  location:
  email: 1460300366@qq.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/petterobam
    - name: instagram
      url:
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url:
    - name: vk
      url:
home:
  section1: <h1>欧阳Boy_Petter</h1>
  section2: <h2>一段文字，一个故事</h2>
  section3: <h2>一段代码，一个故事</h2>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # CC License.
  cc_license_image: /assets/images/theme/cc-by-sa.png # CC License.
  footer_content: github <a href="http://jekyllrb.com/">Jekyll</a> theme.

disqus:
  shortname: # e.g. petterobam
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
  google_analytics: # e.g. 'UA-42456515-5'
  addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

gitment:
  owner: # petterobam
  repo: # blog
  oauth_client_id: # 7d522d338b8d88e40446
  oauth_client_secret: # be5aca84a4c6640f52c48ec546717bcdf297914f

utterances:
  enable: true
  repo: petterobam/blog # owner/repo
  issue_term: pathname # pathname, url, title, og:title [ISSUE NUMBER] or [SPECIFIC TERM]
  theme: # github-light or github-dark

directory: true

live2dgirl: true

paths:
  home: /
  blog: /blog/
  life_news: /life/
  gist: /gist/
  song: /song/
  categories: /blog/categories/
  tags: /blog/tags/
  reader: /reader/
  letter: /letter/
  learner: /learner/
  board: /board/
  qq_zone: /other/QQ/
  pwgen: /other/pwgen/
  gitemoji: /other/gitemoji/
  other: /other/
  family: /family/
  github: https://github.com/petterobam

exclude: ["vendor"]