page:
  title: 我的学习笔记
  inc: 2018 petterObam
  useArgsPathForJar: false  # 如果设置该配置false，jar文件将完全按照配置文件执行，此时mdBasePath、tplPath、indexPath必填
  mdBasePath:  E:\MyMarkdown\zh_CN\学习笔记\  # markdown文件的目录，默认为 classpath:markdowns/
  tplPath: E:\MyMarkdown\zh_CN\学习笔记\install-index\template\index.html   # index模板文件的路径，默认为 classpath:template/index.html
  markdowns:
    - Github博客部署学习笔记.md
    - JVM内存溢出、泄露检查工具学习笔记.md
    - Maven学习笔记.md
    - Git学习笔记.md
    - thymeleaf学习笔记.md
    - grunt学习笔记.md
    - Docker学习笔记.md
    - 3DMax学习笔记.md
  indexPath: E:\MyMarkdown\zh_CN\学习笔记\index.html # 生成的index文件输出路径，默认 classpath:output/index.html
